package enums

const (
	TASK_DETAIL                   = "TASK_DETAIL"
	WORK_LIST_INFO                = "WORK_LIST_INFO"
	SEARCH_TRANSACTION_FUNCTION   = "SEARCH_TRANSACTION_FUNCTION"
	SYSTEM_NOTIFICATION_MESSAGE   = "SYSTEM_NOTIFICATION_MESSAGE"
)