package enums

const (
	ERR_FOREIGN_KEY_VIOLATION = "23503"
	ERR_UNIQUE_VIOLATION      = "23505"
	ERR_CHECK_VIOLATION       = "23514"
	ERR_NOT_NULL_VIOLATION    = "23502"
	ERR_RESTRICT_VIOLATION    = "23001"
	ERR_INVALID_SQL           = "42000"
	ERR_INTERNAL              = "29000"
	ERR_NO_ROWS               = "02000"
)

var ErrCodeSql = map[string]string{
	"00000": "Hoàn thành thành công - Hoạt động được thực thi mà không gặp lỗi.",
	"01000": "Cảnh báo - Thông báo mang tính thông tin cho biết một vấn đề tiềm ẩn nhưng không nhất thiết phải dừng thực thi.",
	"0100C": "Bộ kết quả động được trả về - Truy vấn tạo ra nhiều bộ kết quả hơn dự kiến.",
	"01008": "Bù đệm số 0 ngầm định - Số 0 được tự động thêm vào bên phải của chuỗi bit trong quá trình chuyển đổi dữ liệu.",
	"01003": "Giá trị null bị loại bỏ trong hàm tập - Giá trị NULL được gặp và loại bỏ trong quá trình vận hành tập.",
	"01007": "Quyền truy cập không được cấp - Người dùng không có quyền truy cập cần thiết để thực hiện thao tác được yêu cầu.",
	"01006": "Quyền truy cập không bị thu hồi - Việc thu hồi quyền truy cập đã thử không thành công.",
	"01004": "Cắt bớt dữ liệu chuỗi bên phải - Dữ liệu chuỗi bị cắt bớt vì vượt quá độ dài tối đa cho phép.",
	"01P01": "Tính năng đã lỗi thời - Tính năng được sử dụng đã lỗi thời và có thể bị loại bỏ trong các phiên bản tương lai.",
	"02000": "Không có dữ liệu - Truy vấn không trả về bất kỳ hàng nào.",
	"02001": "Không có bộ kết quả động bổ sung nào được trả về - Không có bộ kết quả nào tiếp theo sau bộ kết quả đầu tiên.",
	"03000": "Lệnh SQL chưa hoàn tất - Lệnh SQL được cung cấp chưa hoàn tất hoặc cần thêm thông tin đầu vào.",
	"04000": "Lỗi cú pháp hoặc vi phạm quy tắc truy cập - Lỗi cú pháp trong truy vấn hoặc vi phạm quy tắc truy cập dữ liệu.",
	"04001": "Lỗi cú pháp trong lệnh SQL - Lỗi cú pháp được phát hiện trong lệnh SQL.",
	"04002": "Lỗi cú pháp trong biểu thức - Lỗi cú pháp được phát hiện trong biểu thức.",
	"04003": "Lỗi cú pháp trong lệnh GRANT - Lỗi cú pháp được phát hiện trong lệnh GRANT.",
	"04004": "Lỗi cú pháp trong lệnh REVOKE - Lỗi cú pháp được phát hiện trong lệnh REVOKE.",
	"04005": "Lỗi cú pháp trong lệnh ALTER TABLE - Lỗi cú pháp được phát hiện trong lệnh ALTER TABLE.",
	"04006": "Lỗi cú pháp trong lệnh CREATE TABLE - Lỗi cú pháp được phát hiện trong lệnh CREATE TABLE.",
	"04007": "Lỗi cú pháp trong lệnh DROP TABLE - Lỗi cú pháp được phát hiện trong lệnh DROP TABLE.",
	"04008": "Lỗi cú pháp trong lệnh CREATE INDEX - Lỗi cú pháp được phát hiện trong lệnh CREATE INDEX.",
	"04009": "Lỗi cú pháp trong lệnh DROP INDEX - Lỗi cú pháp được phát hiện trong lệnh DROP INDEX.",
	"04010": "Lỗi cú pháp trong lệnh CREATE FUNCTION - Lỗi cú pháp được phát hiện trong lệnh CREATE FUNCTION.",
	"04011": "Lỗi cú pháp trong lệnh DROP FUNCTION - Lỗi cú pháp được phát hiện trong lệnh DROP FUNCTION.",
	"04012": "Lỗi cú pháp trong lệnh CREATE VIEW - Lỗi cú pháp được phát hiện trong lệnh CREATE VIEW.",
	"04013": "Lỗi cú pháp trong lệnh DROP VIEW - Lỗi cú pháp được phát hiện trong lệnh DROP VIEW.",
	"04014": "Lỗi cú pháp trong lệnh CREATE TRIGGER - Lỗi cú pháp được phát hiện trong lệnh CREATE TRIGGER.",
	"04015": "Lỗi cú pháp trong lệnh ... (tiếp tục danh sách lỗi cú pháp cho các lệnh khác).",
	"08000": "Ngoại lệ kết nối - Lỗi xảy ra trong quá trình kết nối với cơ sở dữ liệu.",
	"08003": "Kết nối không tồn tại - Kết nối được đề cập không còn tồn tại.",
	"08006": "Lỗi kết nối - Lỗi mạng hoặc lỗi giao thức xảy ra trong quá trình kết nối.",
	"08001": "SQLClient không thể thiết lập kết nối SQL - Lỗi xảy ra khi thư viện SQLClient cố gắng kết nối với cơ sở dữ liệu.",
	"08004": "SQL Server từ chối thiết lập kết nối SQL - Máy chủ SQL từ chối kết nối từ client.",
	"08007": "Giải quyết giao dịch không rõ - Trạng thái giao dịch không rõ ràng.",
	"08P01": "Vi phạm giao thức - Vi phạm giao thức xảy ra trong quá trình kết nối.",
	"09000": "Ngoại lệ hành động kích hoạt - Lỗi xảy ra khi thực thi hành động kích hoạt.",
	"0A000": "Tính năng không được hỗ trợ - Tính năng được yêu cầu không được hỗ trợ bởi phiên bản PostgreSQL hiện tại.",
	"0B000": "Khởi tạo giao dịch không hợp lệ - Lỗi xảy ra khi khởi tạo giao dịch.",
	"0F000": "Ngoại lệ định vị - Lỗi xảy ra khi sử dụng các hàm định vị.",
	"0F001": "Đặc tả định vị không hợp lệ - Định vị được cung cấp không hợp lệ.",
	"0L000": "Người cấp không hợp lệ - Người dùng được chỉ định để cấp quyền không hợp lệ.",
	"0LP01": "Hoạt động cấp quyền không hợp lệ - Hoạt động cấp quyền được yêu cầu không hợp lệ.",
	"0P000": "Đặc tả vai trò không hợp lệ - Vai trò được đề cập không hợp lệ.",
	"0Z000": "Ngoại lệ chẩn đoán - Lỗi xảy ra trong hệ thống chẩn đoán.",
	"0Z002": "Truy cập chẩn đoán xếp chồng mà không có trình xử lý đang hoạt động - Lỗi xảy ra khi truy cập thông tin chẩn đoán mà không có trình xử lý chẩn đoán đang hoạt động.",
	"20000": "Trường hợp không tìm thấy - Trường hợp được đề cập không tồn tại.",
	"21000": "Vi phạm tính toàn vẹn - Lỗi xảy ra do vi phạm ràng buộc tính toàn vẹn dữ liệu.",
	"22000": "Ngoại lệ dữ liệu - Lỗi xảy ra khi xử lý dữ liệu.",
	"2202E": "Lỗi chỉ mục mảng - Chỉ mục mảng không hợp lệ được sử dụng.",
	"22021": "Ký tự không có trong tập ký tự - Ký tự được cung cấp không được hỗ trợ bởi tập ký tự hiện tại.",
	"22008": "Tràn trường datetime - Giá trị quá lớn cho trường datetime.",
	"22012": "Chia cho zero - Lỗi chia cho zero.",
	"22005": "Lỗi trong gán - Lỗi xảy ra trong quá trình gán dữ liệu.",
	"2200B": "Xung đột ký tự thoát - Ký tự thoát được sử dụng không chính xác hoặc xung đột với ký tự khác.",
	"22022": "Tràn chỉ báo - Biến chỉ báo biểu thị sự hiện diện hoặc không có giá trị null bị tràn.",
	"22015": "Tràn trường khoảng - Giá trị quá lớn cho trường khoảng.",
	"2201E": "Đối số không hợp lệ cho logarit - Đối số được cung",
	"2201F": "Đối số không hợp lệ cho hàm lũy thừa - Đối số được cung cấp cho hàm lũy thừa không hợp lệ.",
	"2201G": "Đối số không hợp lệ cho hàm width_bucket - Đối số được cung cấp cho hàm width_bucket không hợp lệ.",
	"22018": "Giá trị ký tự không hợp lệ cho phép chuyển đổi - Giá trị ký tự không hợp lệ được sử dụng cho phép chuyển đổi.",
	"22007": "Định dạng datetime không hợp lệ - Định dạng datetime được cung cấp không hợp lệ.",
	"22019": "Ký tự thoát không hợp lệ - Ký tự thoát được sử dụng không hợp lệ.",
	"2200D": "Byte thoát không hợp lệ - Byte thoát được sử dụng không hợp lệ.",
	"22025": "Trình tự thoát không hợp lệ - Trình tự thoát được sử dụng không hợp lệ.",
	"22P06": "Sử dụng ký tự thoát không chuẩn - Ký tự thoát được sử dụng không theo tiêu chuẩn.",
	"22010": "Giá trị tham số chỉ báo không hợp lệ - Giá trị tham số chỉ báo không hợp lệ.",
	"22023": "Giá trị tham số không hợp lệ - Giá trị tham số được cung cấp không hợp lệ.",
	"22013": "Kích thước trước hoặc sau không hợp lệ - Kích thước trước hoặc sau được cung cấp cho cắt chuỗi không hợp lệ.",
	"2201B": "Biểu thức chính quy không hợp lệ - Biểu thức chính quy được cung cấp không hợp lệ.",
	"2201W": "Số lượng hàng không hợp lệ trong mệnh đề giới hạn - Số lượng hàng được cung cấp cho mệnh đề giới hạn không hợp lệ.",
	"2201X": "Số lượng hàng không hợp lệ trong mệnh đề bù đắp kết quả - Số lượng hàng được cung cấp cho mệnh đề bù đắp kết quả không hợp lệ.",
	"2202H": "Đối số mẫu bảng không hợp lệ - Đối số được cung cấp cho mẫu bảng không hợp lệ.",
	"2202G": "Lặp lại mẫu bảng không hợp lệ - Lặp lại mẫu bảng được cung cấp không hợp lệ.",
	"22009": "Giá trị dịch chuyển múi giờ không hợp lệ - Giá trị dịch chuyển múi giờ được cung cấp không hợp lệ.",
	"2200C": "Sử dụng ký tự thoát không hợp lệ - Ký tự thoát được sử dụng không theo tiêu chuẩn.",
	"2200G": "Loại không khớp cụ thể nhất - Loại dữ liệu thực tế không khớp với loại dữ liệu mong muốn.",
	"22004": "Giá trị null không được phép - Giá trị null không được phép trong trường hợp này.",
	"22002": "Giá trị null không có tham số chỉ báo - Tham số chỉ báo không được cung cấp cho giá trị null.",
	"22003": "Giá trị số vượt quá phạm vi - Giá trị số vượt quá phạm vi cho phép cho kiểu dữ liệu.",
	"2200H": "Giới hạn máy tạo chuỗi bị vượt quá - Số lượng chuỗi được tạo bởi máy tạo chuỗi vượt quá giới hạn.",
	"22026": "Chiều dài dữ liệu chuỗi không khớp - Chiều dài dữ liệu chuỗi không khớp với định dạng mong muốn.",
	"22001": "Cắt bớt dữ liệu chuỗi bên phải - Dữ liệu chuỗi bị cắt bớt vì vượt quá độ dài tối đa cho phép.",
	"22011": "Lỗi cắt chuỗi - Lỗi xảy ra khi cắt chuỗi.",
	"22027": "Lỗi cắt xén - Lỗi xảy ra khi cắt xén chuỗi.",
	"22024": "Chuỗi C không kết thúc - Chuỗi C được cung cấp không được kết thúc bằng ký tự null.",
	"2200F": "Chuỗi ký tự có độ dài bằng 0 - Chuỗi ký tự rỗng được cung cấp.",
	"22P01": "Ngoại lệ dấu phẩy động - Lỗi xảy ra trong quá trình xử lý số dấu phẩy động.",
	"22P02": "Biểu diễn văn bản không hợp lệ - Biểu diễn văn bản của dữ liệu không hợp lệ.",
	"22P03": "Biểu diễn nhị phân không hợp lệ - Biểu diễn nhị phân của dữ liệu không hợp lệ.",
	"22P04": "Định dạng tệp sao chép không tốt - Định dạng tệp được sử dụng cho sao chép không hợp lệ.",
	"22P05": "Ký tự không thể dịch - Ký tự không thể được biểu diễn trong tập ký tự hiện tại.",
	"2200L": "Không phải là tài liệu XML - Dữ liệu được cung cấp không phải là tài liệu XML hợp lệ.",
	"2200M": "Tài liệu XML không hợp lệ - Lỗi cú pháp được phát hiện trong tài liệu XML.",
	"2200N": "Nội dung XML không hợp lệ - Lỗi nội dung được phát hiện trong tài liệu XML.",
	"2200S": "Bình luận XML không hợp lệ - Lỗi cú pháp được phát hiện trong bình luận XML.",
	"2200T": "Hướng dẫn xử lý XML không hợp lệ - Lỗi cú pháp được phát hiện trong hướng dẫn xử lý XML.",
	"22030": "Giá trị khóa-giá trị trùng lặp trong JSON - Khóa trùng lặp được phát hiện trong đối tượng JSON.",
	"22031": "Đối số không hợp lệ cho hàm datetime JSON SQL - Đối số được cung cấp cho hàm datetime JSON SQL không hợp lệ.",
	"22032": "Văn bản JSON không hợp lệ - Dữ liệu được cung cấp không phải là văn bản JSON hợp lệ.",
	"22033": "Chỉ mục JSON SQL không hợp lệ - Chỉ mục được cung cấp cho truy vấn JSON SQL không hợp lệ.",
	"22034": "Nhiều hơn một mục JSON SQL - Hơn một mục được tìm thấy trong truy vấn JSON SQL, trong khi chỉ một mục được mong đợi.",
	"22035": "Không có mục JSON SQL - Không có mục nào được tìm thấy trong truy vấn JSON SQL, trong khi ít nhất một mục được mong đợi.",
	"22036": "Mục JSON SQL không phải là số - Mục được tìm thấy trong truy vấn JSON SQL không phải là số.",
	"22037": "Khóa không duy nhất trong đối tượng JSON - Khóa không duy nhất được phát hiện trong đối tượng JSON.",
	"22038": "Mục JSON SQL đơn lẻ được yêu cầu - Truy vấn JSON SQL yêu cầu một mục, nhưng nhiều mục được tìm thấy.",
	"22039": "Mảng JSON SQL không tìm thấy - Mảng JSON được đề cập trong truy vấn không được tìm thấy.",
	"2203A": "Thành viên JSON SQL không tìm thấy - Thành viên JSON được đề cập trong truy vấn không được tìm thấy.",
	"2203B": "Số JSON SQL không tìm thấy - Số JSON được đề cập trong truy vấn không được tìm thấy.",
	"2203C": "Đối tượng JSON SQL không tìm thấy - Đối tượng JSON được đề cập trong truy vấn không được tìm thấy.",
	"2203D": "Quá nhiều phần tử mảng JSON - Mảng JSON có nhiều phần tử hơn cho phép.",
	"2203E": "Quá nhiều thành viên đối tượng JSON - Đối tượng JSON có nhiều thành viên hơn cho phép.",
	"2203F": "Giá trị vô hướng JSON SQL được yêu cầu - Truy vấn JSON SQL yêu cầu một giá trị vô hướng, nhưng một mảng hoặc đối tượng được tìm thấy.",
	"2203G": "Mục JSON SQL không thể chuyển đổi sang kiểu đích - Mục JSON không thể được chuyển đổi sang kiểu dữ liệu đích được yêu cầu.",
	"23000": "Vi phạm ràng buộc dữ liệu toàn vẹn - Lỗi xảy ra do vi phạm ràng buộc toàn vẹn dữ liệu.",
	"23001": "Vi phạm ràng buộc RESTRICT - Vi phạm ràng buộc RESTRICT xảy ra.",
	"23502": "Vi phạm NOT NULL - Giá trị null được cung cấp cho trường NOT NULL.",
	"23503": "Vi phạm khóa ngoại - Khóa ngoại được tham chiếu không tồn tại.",
	"23505": "Vi phạm duy nhất - Giá trị được cung cấp cho trường duy nhất đã tồn tại.",
	"23514": "Vi phạm CHECK - Giá trị không thỏa mãn ràng buộc CHECK.",
	"23P01": "Vi phạm ràng buộc loại - Giá trị được cung cấp không phù hợp với loại dữ liệu mong muốn.",
	"24000": "Lỗi trích xuất giá trị - Lỗi xảy ra khi trích xuất giá trị từ dữ liệu.",
	"25000": "Lỗi chuyển đổi - Lỗi xảy ra khi chuyển đổi dữ liệu từ kiểu dữ liệu này sang kiểu dữ liệu khác.",
	"26000": "Lỗi truy cập tập tin - Lỗi xảy ra khi truy cập tập tin.",
	"27000": "Lỗi không đủ bộ nhớ - Hệ thống không có đủ bộ nhớ để thực hiện thao tác.",
	"28000": "Lỗi quá tải tài nguyên - Hệ thống đang quá tải và không thể thực hiện thêm thao tác.",
	"29000": "Lỗi nghiêm trọng - Lỗi nghiêm trọng xảy ra trong hệ thống.",
	"38000": "Lỗi xác thực - Lỗi xảy ra trong quá trình xác thực người dùng.",
	"38001": "Lỗi mật khẩu sai - Mật khẩu được cung cấp không chính xác.",
	"38002": "Tên người dùng không tồn tại - Tên người dùng được cung cấp không tồn tại.",
	"38P01": "Lỗi xác thực Kerberos - Lỗi xảy ra trong quá trình xác thực Kerberos.",
	"39000": "Lỗi bảo mật - Lỗi bảo mật xảy ra trong hệ thống.",
	"40000": "Lỗi giao dịch - Lỗi xảy ra trong quá trình thực thi giao dịch.",
	"40001": "Lỗi xung đột giao dịch - Xung đột xảy ra giữa hai hoặc nhiều giao dịch.",
	"40002": "Lỗi giới hạn thời gian giao dịch - Giao dịch vượt quá thời gian chờ cho phép.",
	"40003": "Lỗi hủy giao dịch - Giao dịch bị hủy do lỗi.",
	"40P01": "Lỗi khóa giao dịch - Lỗi xảy ra khi cố gắng lấy hoặc giải phóng khóa giao dịch.",
	"42000": "Lỗi chương trình - Lỗi xảy ra trong chương trình ứng dụng.",
	"42601": "Lỗi cú pháp SQL - Lỗi cú pháp được phát hiện trong lệnh SQL.",
	"42611": "Lỗi tham số không hợp lệ - Tham số được cung cấp cho hàm không hợp lệ.",
	"42622": "Lỗi truy cập bộ nhớ - Lỗi truy cập bộ nhớ không hợp lệ xảy ra.",
	"42803": "Lỗi toán học - Lỗi tràn hoặc chia cho zero xảy ra trong quá trình tính toán.",
	"42P01": "Lỗi tràn bộ đệm - Lỗi tràn bộ đệm xảy ra trong chương trình ứng dụng.",
	"44000": "Lỗi liên quan đến kết nối - Lỗi xảy ra trong quá trình kết nối với cơ sở dữ liệu.",
	"53000": "Lỗi lưu trữ - Lỗi xảy ra trong hệ thống lưu trữ.",
	"54000": "Lỗi hệ thống - Lỗi hệ thống xảy ra trong hệ điều hành.",
	"55000": "Lỗi dữ liệu ứng dụng - Lỗi xảy ra trong dữ liệu ứng dụng.",
	"57000": "Lỗi thời gian thực - Lỗi xảy ra trong hệ thống thời gian thực.",
	"58000": "Lỗi điểm truy cập - Lỗi xảy ra trong hệ thống điểm truy cập.",
	"F0000": "Lỗi đặc biệt của người dùng - Lỗi do người dùng tạo ra.",
	"HV000": "Lỗi trình xem - Lỗi xảy ra trong trình xem.",
	"P0000": "Lỗi liên quan đến PL/pgSQL - Lỗi xảy ra trong ngôn ngữ PL/pgSQL.",
	"P0001": "Lỗi cú pháp PL/pgSQL - Lỗi cú pháp được phát hiện trong mã PL/pgSQL.",
	"P0002": "Lỗi thời gian thực PL/pgSQL - Lỗi xảy ra trong quá trình thực thi mã PL/pgSQL.",
	"P0003": "Lỗi ngoại lệ PL/pgSQL - Lỗi ngoại lệ được ném trong mã PL/pgSQL.",
	"P0004": "Lỗi không đủ bộ nhớ PL/pgSQL - Hệ thống không có đủ bộ nhớ để thực thi mã PL/pgSQL.",
	"P0005": "Lỗi truy cập tập tin PL/pgSQL - Lỗi xảy ra khi truy cập tập tin trong mã PL/pgSQL.",
	"P0006": "Lỗi không tìm thấy hàm PL/pgSQL - Hàm PL/pgSQL được đề cập không được tìm thấy.",
	"P0007": "Lỗi loại dữ liệu PL/pgSQL - Lỗi xảy ra do không khớp loại dữ liệu trong mã PL/pgSQL.",
	"P0008": "Lỗi tràn bộ đệm PL/pgSQL - Lỗi tràn bộ đệm xảy ra trong mã PL/pgSQL.",
	"P0009": "Lỗi chia cho zero PL/pgSQL - Lỗi chia cho zero xảy ra trong mã PL/pgSQL.",
	"P0010": "Lỗi tràn số PL/pgSQL - Lỗi tràn số xảy ra trong mã PL/pgSQL.",
	"P0011": "Lỗi truy cập bộ nhớ PL/pgSQL - Lỗi truy cập bộ nhớ không hợp lệ xảy ra trong mã PL/pgSQL.",
	"P0012": "Lỗi hủy PL/pgSQL - Lỗi hủy xảy ra trong mã PL/pgSQL.",
	"P0013": "Lỗi PL/pgSQL không xác định - Lỗi không xác định xảy ra trong mã PL/pgSQL.",
	"XX000": "Lỗi cụ thể của nhà cung cấp - Lỗi do nhà cung cấp cụ thể tạo ra.",
}


