basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@petcare.io
    name: API Support
    url: http://www.petcare.io/support
  description: API Server for Pet Care Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Pet Care API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Get the status of the server and its services
      produces:
      - application/json
      responses:
        "200":
          description: Health check response
          schema:
            additionalProperties: true
            type: object
      summary: Health check endpoint
      tags:
      - health
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
