basePath: /
definitions:
  user.VerrifyEmailTxParams:
    properties:
      secret_code:
        type: integer
      username:
        type: string
    type: object
host: localhost:8088
info:
  contact:
    email: vbhadauriya@redcloudcomputing.com
    name: Vivek Singh
    url: https://github.com/san-data-systems
  description: 1View Blog Portal Rest API documentation
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  termsOfService: https://swagger.io/terms/
  title: 1View Blog Portal
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user with the input payload
      parameters:
      - description: User data
        in: formData
        name: data
        required: true
        type: string
      - description: User image
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.VerrifyEmailTxParams'
      security:
      - ApiKeyAuth: []
      summary: Create a new user
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    description: JWT Authorization header using the Bearer scheme.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
