// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: appoinment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAppointmentsByDateAndTimeSlot = `-- name: CountAppointmentsByDateAndTimeSlot :one
SELECT COUNT(*) 
FROM appointments 
WHERE date = $1 AND doctor_id = $2 AND status = 'completed'
`

type CountAppointmentsByDateAndTimeSlotParams struct {
	Date     pgtype.Timestamp `json:"date"`
	DoctorID pgtype.Int8      `json:"doctor_id"`
}

func (q *Queries) CountAppointmentsByDateAndTimeSlot(ctx context.Context, arg CountAppointmentsByDateAndTimeSlotParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppointmentsByDateAndTimeSlot, arg.Date, arg.DoctorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (petid, username, doctor_id, service_id, date, time_slot_id, state_id)
VALUES ($1, $2, $3, $4, $5, $6, (SELECT id FROM states WHERE state = 'Scheduled'))
RETURNING appointment_id, petid, username, doctor_id, service_id, date, notes, reminder_send, time_slot_id, created_at, state_id
`

type CreateAppointmentParams struct {
	Petid      pgtype.Int8      `json:"petid"`
	Username   pgtype.Text      `json:"username"`
	DoctorID   pgtype.Int8      `json:"doctor_id"`
	ServiceID  pgtype.Int8      `json:"service_id"`
	Date       pgtype.Timestamp `json:"date"`
	TimeSlotID pgtype.Int8      `json:"time_slot_id"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.Petid,
		arg.Username,
		arg.DoctorID,
		arg.ServiceID,
		arg.Date,
		arg.TimeSlotID,
	)
	var i Appointment
	err := row.Scan(
		&i.AppointmentID,
		&i.Petid,
		&i.Username,
		&i.DoctorID,
		&i.ServiceID,
		&i.Date,
		&i.Notes,
		&i.ReminderSend,
		&i.TimeSlotID,
		&i.CreatedAt,
		&i.StateID,
	)
	return i, err
}

const getAllAppointments = `-- name: GetAllAppointments :many
SELECT appointment_id, appointments.petid, appointments.username, appointments.doctor_id, service_id, appointments.date, notes, reminder_send, time_slot_id, appointments.created_at, state_id, pets.petid, pets.name, type, breed, age, gender, healthnotes, weight, birth_date, pets.username, microchip_number, last_checkup_date, is_active, data_image, original_image, services.id, services.name, description, duration, cost, category, priority, services.created_at, time_slots.id, time_slots.doctor_id, time_slots.date, start_time, end_time, max_patients, booked_patients, time_slots.created_at, updated_at, shift_id, doctors.id, user_id, specialization, years_of_experience, education, certificate_number, bio FROM appointments
JOIN pets ON appointments.petid = pets.petid
JOIN services ON appointments.service_id = services.id
JOIN time_slots ON appointments.time_slot_id = time_slots.id
JOIN doctors ON appointments.doctor_id = doctors.id
`

type GetAllAppointmentsRow struct {
	AppointmentID     int64            `json:"appointment_id"`
	Petid             pgtype.Int8      `json:"petid"`
	Username          pgtype.Text      `json:"username"`
	DoctorID          pgtype.Int8      `json:"doctor_id"`
	ServiceID         pgtype.Int8      `json:"service_id"`
	Date              pgtype.Timestamp `json:"date"`
	Notes             pgtype.Text      `json:"notes"`
	ReminderSend      pgtype.Bool      `json:"reminder_send"`
	TimeSlotID        pgtype.Int8      `json:"time_slot_id"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	StateID           pgtype.Int4      `json:"state_id"`
	Petid_2           int64            `json:"petid_2"`
	Name              string           `json:"name"`
	Type              string           `json:"type"`
	Breed             pgtype.Text      `json:"breed"`
	Age               pgtype.Int4      `json:"age"`
	Gender            pgtype.Text      `json:"gender"`
	Healthnotes       pgtype.Text      `json:"healthnotes"`
	Weight            pgtype.Float8    `json:"weight"`
	BirthDate         pgtype.Date      `json:"birth_date"`
	Username_2        string           `json:"username_2"`
	MicrochipNumber   pgtype.Text      `json:"microchip_number"`
	LastCheckupDate   pgtype.Date      `json:"last_checkup_date"`
	IsActive          pgtype.Bool      `json:"is_active"`
	DataImage         []byte           `json:"data_image"`
	OriginalImage     pgtype.Text      `json:"original_image"`
	ID                int64            `json:"id"`
	Name_2            pgtype.Text      `json:"name_2"`
	Description       pgtype.Text      `json:"description"`
	Duration          pgtype.Int2      `json:"duration"`
	Cost              pgtype.Float8    `json:"cost"`
	Category          pgtype.Text      `json:"category"`
	Priority          pgtype.Int2      `json:"priority"`
	CreatedAt_2       pgtype.Timestamp `json:"created_at_2"`
	ID_2              int64            `json:"id_2"`
	DoctorID_2        int32            `json:"doctor_id_2"`
	Date_2            pgtype.Date      `json:"date_2"`
	StartTime         pgtype.Time      `json:"start_time"`
	EndTime           pgtype.Time      `json:"end_time"`
	MaxPatients       pgtype.Int4      `json:"max_patients"`
	BookedPatients    pgtype.Int4      `json:"booked_patients"`
	CreatedAt_3       pgtype.Timestamp `json:"created_at_3"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	ShiftID           int64            `json:"shift_id"`
	ID_3              int64            `json:"id_3"`
	UserID            int64            `json:"user_id"`
	Specialization    pgtype.Text      `json:"specialization"`
	YearsOfExperience pgtype.Int4      `json:"years_of_experience"`
	Education         pgtype.Text      `json:"education"`
	CertificateNumber pgtype.Text      `json:"certificate_number"`
	Bio               pgtype.Text      `json:"bio"`
}

func (q *Queries) GetAllAppointments(ctx context.Context) ([]GetAllAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, getAllAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllAppointmentsRow{}
	for rows.Next() {
		var i GetAllAppointmentsRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.Petid,
			&i.Username,
			&i.DoctorID,
			&i.ServiceID,
			&i.Date,
			&i.Notes,
			&i.ReminderSend,
			&i.TimeSlotID,
			&i.CreatedAt,
			&i.StateID,
			&i.Petid_2,
			&i.Name,
			&i.Type,
			&i.Breed,
			&i.Age,
			&i.Gender,
			&i.Healthnotes,
			&i.Weight,
			&i.BirthDate,
			&i.Username_2,
			&i.MicrochipNumber,
			&i.LastCheckupDate,
			&i.IsActive,
			&i.DataImage,
			&i.OriginalImage,
			&i.ID,
			&i.Name_2,
			&i.Description,
			&i.Duration,
			&i.Cost,
			&i.Category,
			&i.Priority,
			&i.CreatedAt_2,
			&i.ID_2,
			&i.DoctorID_2,
			&i.Date_2,
			&i.StartTime,
			&i.EndTime,
			&i.MaxPatients,
			&i.BookedPatients,
			&i.CreatedAt_3,
			&i.UpdatedAt,
			&i.ShiftID,
			&i.ID_3,
			&i.UserID,
			&i.Specialization,
			&i.YearsOfExperience,
			&i.Education,
			&i.CertificateNumber,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentByStateId = `-- name: GetAppointmentByStateId :many
SELECT appointment_id, petid, username, doctor_id, service_id, date, notes, reminder_send, time_slot_id, created_at, state_id FROM appointments WHERE state_id = $1
`

func (q *Queries) GetAppointmentByStateId(ctx context.Context, stateID pgtype.Int4) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getAppointmentByStateId, stateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.AppointmentID,
			&i.Petid,
			&i.Username,
			&i.DoctorID,
			&i.ServiceID,
			&i.Date,
			&i.Notes,
			&i.ReminderSend,
			&i.TimeSlotID,
			&i.CreatedAt,
			&i.StateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentDetailById = `-- name: GetAppointmentDetailById :one
SELECT appointment_id, petid, username, doctor_id, service_id, date, notes, reminder_send, time_slot_id, created_at, state_id from appointments WHERE appointment_id = $1
`

func (q *Queries) GetAppointmentDetailById(ctx context.Context, appointmentID int64) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentDetailById, appointmentID)
	var i Appointment
	err := row.Scan(
		&i.AppointmentID,
		&i.Petid,
		&i.Username,
		&i.DoctorID,
		&i.ServiceID,
		&i.Date,
		&i.Notes,
		&i.ReminderSend,
		&i.TimeSlotID,
		&i.CreatedAt,
		&i.StateID,
	)
	return i, err
}

const getAppointmentsByDoctor = `-- name: GetAppointmentsByDoctor :many
SELECT 
    a.appointment_id, a.petid, a.username, a.doctor_id, a.service_id, a.date, a.notes, a.reminder_send, a.time_slot_id, a.created_at, a.state_id,
    d.id AS doctor_id,
    p.name AS pet_name,
    s.name AS service_name,
    ts.start_time,
    ts.end_time
FROM 
    appointments a
JOIN 
    doctors d ON a.doctor_id = d.id
JOIN 
    pets p ON a.petid = p.petid
JOIN 
    services as s ON a.service_id = s.id
JOIN 
    time_slots ts ON a.time_slot_id = ts.id
WHERE 
    a.doctor_id = $1
`

type GetAppointmentsByDoctorRow struct {
	AppointmentID int64            `json:"appointment_id"`
	Petid         pgtype.Int8      `json:"petid"`
	Username      pgtype.Text      `json:"username"`
	DoctorID      pgtype.Int8      `json:"doctor_id"`
	ServiceID     pgtype.Int8      `json:"service_id"`
	Date          pgtype.Timestamp `json:"date"`
	Notes         pgtype.Text      `json:"notes"`
	ReminderSend  pgtype.Bool      `json:"reminder_send"`
	TimeSlotID    pgtype.Int8      `json:"time_slot_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	StateID       pgtype.Int4      `json:"state_id"`
	DoctorID_2    int64            `json:"doctor_id_2"`
	PetName       string           `json:"pet_name"`
	ServiceName   pgtype.Text      `json:"service_name"`
	StartTime     pgtype.Time      `json:"start_time"`
	EndTime       pgtype.Time      `json:"end_time"`
}

func (q *Queries) GetAppointmentsByDoctor(ctx context.Context, doctorID pgtype.Int8) ([]GetAppointmentsByDoctorRow, error) {
	rows, err := q.db.Query(ctx, getAppointmentsByDoctor, doctorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppointmentsByDoctorRow{}
	for rows.Next() {
		var i GetAppointmentsByDoctorRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.Petid,
			&i.Username,
			&i.DoctorID,
			&i.ServiceID,
			&i.Date,
			&i.Notes,
			&i.ReminderSend,
			&i.TimeSlotID,
			&i.CreatedAt,
			&i.StateID,
			&i.DoctorID_2,
			&i.PetName,
			&i.ServiceName,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsByUser = `-- name: GetAppointmentsByUser :many
SELECT 
    p.petid, p.name, p.type, p.breed, p.age, p.gender, p.healthnotes, p.weight, p.birth_date, p.username, p.microchip_number, p.last_checkup_date, p.is_active, p.data_image, p.original_image, s.id, s.name, s.description, s.duration, s.cost, s.category, s.priority, s.created_at, a.appointment_id, a.petid, a.username, a.doctor_id, a.service_id, a.date, a.notes, a.reminder_send, a.time_slot_id, a.created_at, a.state_id, ts.id, ts.doctor_id, ts.date, ts.start_time, ts.end_time, ts.max_patients, ts.booked_patients, ts.created_at, ts.updated_at, ts.shift_id
FROM 
    appointments a
JOIN 
    pets p ON a.petid = p.petid 
JOIN 
    services s ON a.service_id = s.id 
JOIN 
    time_slots ts ON a.time_slot_id = ts.id
WHERE 
    a.username = $1 and a.status <> 'completed'
`

type GetAppointmentsByUserRow struct {
	Petid           int64            `json:"petid"`
	Name            string           `json:"name"`
	Type            string           `json:"type"`
	Breed           pgtype.Text      `json:"breed"`
	Age             pgtype.Int4      `json:"age"`
	Gender          pgtype.Text      `json:"gender"`
	Healthnotes     pgtype.Text      `json:"healthnotes"`
	Weight          pgtype.Float8    `json:"weight"`
	BirthDate       pgtype.Date      `json:"birth_date"`
	Username        string           `json:"username"`
	MicrochipNumber pgtype.Text      `json:"microchip_number"`
	LastCheckupDate pgtype.Date      `json:"last_checkup_date"`
	IsActive        pgtype.Bool      `json:"is_active"`
	DataImage       []byte           `json:"data_image"`
	OriginalImage   pgtype.Text      `json:"original_image"`
	ID              int64            `json:"id"`
	Name_2          pgtype.Text      `json:"name_2"`
	Description     pgtype.Text      `json:"description"`
	Duration        pgtype.Int2      `json:"duration"`
	Cost            pgtype.Float8    `json:"cost"`
	Category        pgtype.Text      `json:"category"`
	Priority        pgtype.Int2      `json:"priority"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	AppointmentID   int64            `json:"appointment_id"`
	Petid_2         pgtype.Int8      `json:"petid_2"`
	Username_2      pgtype.Text      `json:"username_2"`
	DoctorID        pgtype.Int8      `json:"doctor_id"`
	ServiceID       pgtype.Int8      `json:"service_id"`
	Date            pgtype.Timestamp `json:"date"`
	Notes           pgtype.Text      `json:"notes"`
	ReminderSend    pgtype.Bool      `json:"reminder_send"`
	TimeSlotID      pgtype.Int8      `json:"time_slot_id"`
	CreatedAt_2     pgtype.Timestamp `json:"created_at_2"`
	StateID         pgtype.Int4      `json:"state_id"`
	ID_2            int64            `json:"id_2"`
	DoctorID_2      int32            `json:"doctor_id_2"`
	Date_2          pgtype.Date      `json:"date_2"`
	StartTime       pgtype.Time      `json:"start_time"`
	EndTime         pgtype.Time      `json:"end_time"`
	MaxPatients     pgtype.Int4      `json:"max_patients"`
	BookedPatients  pgtype.Int4      `json:"booked_patients"`
	CreatedAt_3     pgtype.Timestamp `json:"created_at_3"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	ShiftID         int64            `json:"shift_id"`
}

func (q *Queries) GetAppointmentsByUser(ctx context.Context, username pgtype.Text) ([]GetAppointmentsByUserRow, error) {
	rows, err := q.db.Query(ctx, getAppointmentsByUser, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppointmentsByUserRow{}
	for rows.Next() {
		var i GetAppointmentsByUserRow
		if err := rows.Scan(
			&i.Petid,
			&i.Name,
			&i.Type,
			&i.Breed,
			&i.Age,
			&i.Gender,
			&i.Healthnotes,
			&i.Weight,
			&i.BirthDate,
			&i.Username,
			&i.MicrochipNumber,
			&i.LastCheckupDate,
			&i.IsActive,
			&i.DataImage,
			&i.OriginalImage,
			&i.ID,
			&i.Name_2,
			&i.Description,
			&i.Duration,
			&i.Cost,
			&i.Category,
			&i.Priority,
			&i.CreatedAt,
			&i.AppointmentID,
			&i.Petid_2,
			&i.Username_2,
			&i.DoctorID,
			&i.ServiceID,
			&i.Date,
			&i.Notes,
			&i.ReminderSend,
			&i.TimeSlotID,
			&i.CreatedAt_2,
			&i.StateID,
			&i.ID_2,
			&i.DoctorID_2,
			&i.Date_2,
			&i.StartTime,
			&i.EndTime,
			&i.MaxPatients,
			&i.BookedPatients,
			&i.CreatedAt_3,
			&i.UpdatedAt,
			&i.ShiftID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsOfDoctorWithDetails = `-- name: GetAppointmentsOfDoctorWithDetails :many
SELECT 
    a.appointment_id as appointment_id,
    p.name as pet_name,
    s.name as service_name,
    ts.start_time,
    ts.end_time
FROM appointments a
    LEFT JOIN doctors d ON a.doctor_id = d.id
    LEFT JOIN pets p ON a.petid = p.petid
    LEFT JOIN services s ON a.service_id = s.id
    LEFT JOIN time_slots ts ON a.time_slot_id = ts.id
WHERE d.id = $1
AND LOWER(a.status) <> 'completed'
ORDER BY ts.start_time ASC
`

type GetAppointmentsOfDoctorWithDetailsRow struct {
	AppointmentID int64       `json:"appointment_id"`
	PetName       pgtype.Text `json:"pet_name"`
	ServiceName   pgtype.Text `json:"service_name"`
	StartTime     pgtype.Time `json:"start_time"`
	EndTime       pgtype.Time `json:"end_time"`
}

func (q *Queries) GetAppointmentsOfDoctorWithDetails(ctx context.Context, id int64) ([]GetAppointmentsOfDoctorWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getAppointmentsOfDoctorWithDetails, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppointmentsOfDoctorWithDetailsRow{}
	for rows.Next() {
		var i GetAppointmentsOfDoctorWithDetailsRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.PetName,
			&i.ServiceName,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSOAPByAppointmentID = `-- name: GetSOAPByAppointmentID :one
SELECT id, appointment_id, subjective, objective, assessment, plan, created_at FROM consultations WHERE appointment_id = $1
`

func (q *Queries) GetSOAPByAppointmentID(ctx context.Context, appointmentID pgtype.Int8) (Consultation, error) {
	row := q.db.QueryRow(ctx, getSOAPByAppointmentID, appointmentID)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.Subjective,
		&i.Objective,
		&i.Assessment,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const listAllAppointments = `-- name: ListAllAppointments :many
SELECT appointment_id, petid, username, doctor_id, service_id, date, notes, reminder_send, time_slot_id, created_at, state_id FROM appointments
`

func (q *Queries) ListAllAppointments(ctx context.Context) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAllAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.AppointmentID,
			&i.Petid,
			&i.Username,
			&i.DoctorID,
			&i.ServiceID,
			&i.Date,
			&i.Notes,
			&i.ReminderSend,
			&i.TimeSlotID,
			&i.CreatedAt,
			&i.StateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointmentByID = `-- name: UpdateAppointmentByID :exec
UPDATE appointments SET 
    state_id = $2,
    notes = $3,
    reminder_send = $4,
    updated_at = now()
WHERE appointment_id = $1
`

type UpdateAppointmentByIDParams struct {
	AppointmentID int64       `json:"appointment_id"`
	StateID       pgtype.Int4 `json:"state_id"`
	Notes         pgtype.Text `json:"notes"`
	ReminderSend  pgtype.Bool `json:"reminder_send"`
}

func (q *Queries) UpdateAppointmentByID(ctx context.Context, arg UpdateAppointmentByIDParams) error {
	_, err := q.db.Exec(ctx, updateAppointmentByID,
		arg.AppointmentID,
		arg.StateID,
		arg.Notes,
		arg.ReminderSend,
	)
	return err
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :exec
UPDATE appointments
SET state_id = $2
WHERE appointment_id = $1
`

type UpdateAppointmentStatusParams struct {
	AppointmentID int64       `json:"appointment_id"`
	StateID       pgtype.Int4 `json:"state_id"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAppointmentStatus, arg.AppointmentID, arg.StateID)
	return err
}

const updateNotification = `-- name: UpdateNotification :exec
UPDATE appointments
SET reminder_send = true
WHERE appointment_id = $1
`

func (q *Queries) UpdateNotification(ctx context.Context, appointmentID int64) error {
	_, err := q.db.Exec(ctx, updateNotification, appointmentID)
	return err
}

const updateTimeSlotBookedPatients = `-- name: UpdateTimeSlotBookedPatients :exec
UPDATE time_slots
SET booked_patients = booked_patients + 1
WHERE id = $1
`

func (q *Queries) UpdateTimeSlotBookedPatients(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateTimeSlotBookedPatients, id)
	return err
}
