// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: diseases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDiceaseAndMedicinesInfo = `-- name: GetDiceaseAndMedicinesInfo :many
SELECT 
    d.id AS disease_id,
    d.name AS disease_name,
    d.description AS disease_description,
    d.symptoms,
    m.id AS medicine_id,
    m.name AS medicine_name,
    m.usage AS medicine_usage,
    m.dosage,
    m.frequency,
    m.duration,
    m.side_effects
FROM diseases d
LEFT JOIN disease_medicines dm ON d.id = dm.disease_id
LEFT JOIN medicines m ON dm.medicine_id = m.id
WHERE LOWER(d.name) LIKE LOWER($1)
`

type GetDiceaseAndMedicinesInfoRow struct {
	DiseaseID          int64       `json:"disease_id"`
	DiseaseName        string      `json:"disease_name"`
	DiseaseDescription pgtype.Text `json:"disease_description"`
	Symptoms           []byte      `json:"symptoms"`
	MedicineID         pgtype.Int8 `json:"medicine_id"`
	MedicineName       pgtype.Text `json:"medicine_name"`
	MedicineUsage      pgtype.Text `json:"medicine_usage"`
	Dosage             pgtype.Text `json:"dosage"`
	Frequency          pgtype.Text `json:"frequency"`
	Duration           pgtype.Text `json:"duration"`
	SideEffects        pgtype.Text `json:"side_effects"`
}

// 1. Query cơ bản để lấy thông tin bệnh và thuốc điều trị
func (q *Queries) GetDiceaseAndMedicinesInfo(ctx context.Context, lower string) ([]GetDiceaseAndMedicinesInfoRow, error) {
	rows, err := q.db.Query(ctx, getDiceaseAndMedicinesInfo, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiceaseAndMedicinesInfoRow{}
	for rows.Next() {
		var i GetDiceaseAndMedicinesInfoRow
		if err := rows.Scan(
			&i.DiseaseID,
			&i.DiseaseName,
			&i.DiseaseDescription,
			&i.Symptoms,
			&i.MedicineID,
			&i.MedicineName,
			&i.MedicineUsage,
			&i.Dosage,
			&i.Frequency,
			&i.Duration,
			&i.SideEffects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiseaseTreatmentPlanWithPhases = `-- name: GetDiseaseTreatmentPlanWithPhases :many
SELECT 
    d.id AS disease_id,
    d.name AS disease_name,
    d.description AS disease_description,
    d.symptoms,
    tp.phase_name,
    tp.description AS phase_description,
    m.id AS medicine_id,
    m.usage AS medicine_usage,
    m.name AS medicine_name,
    m.description AS medicine_description,
    pm.phase_id AS phase_id,
    COALESCE(pm.dosage, m.dosage) AS dosage,
    COALESCE(pm.frequency, m.frequency) AS frequency,
    COALESCE(pm.duration, m.duration) AS duration,
    m.side_effects,
    pm.notes AS medicine_notes
FROM diseases d
JOIN treatment_phases tp ON d.id = tp.disease_id
JOIN phase_medicines pm ON tp.id = pm.phase_id
JOIN medicines m ON pm.medicine_id = m.id
WHERE LOWER(d.name) LIKE LOWER($1)
ORDER BY tp.start_date, m.name
`

type GetDiseaseTreatmentPlanWithPhasesRow struct {
	DiseaseID           int64       `json:"disease_id"`
	DiseaseName         string      `json:"disease_name"`
	DiseaseDescription  pgtype.Text `json:"disease_description"`
	Symptoms            []byte      `json:"symptoms"`
	PhaseName           pgtype.Text `json:"phase_name"`
	PhaseDescription    pgtype.Text `json:"phase_description"`
	MedicineID          int64       `json:"medicine_id"`
	MedicineUsage       pgtype.Text `json:"medicine_usage"`
	MedicineName        string      `json:"medicine_name"`
	MedicineDescription pgtype.Text `json:"medicine_description"`
	PhaseID             int64       `json:"phase_id"`
	Dosage              pgtype.Text `json:"dosage"`
	Frequency           pgtype.Text `json:"frequency"`
	Duration            pgtype.Text `json:"duration"`
	SideEffects         pgtype.Text `json:"side_effects"`
	MedicineNotes       pgtype.Text `json:"medicine_notes"`
}

func (q *Queries) GetDiseaseTreatmentPlanWithPhases(ctx context.Context, lower string) ([]GetDiseaseTreatmentPlanWithPhasesRow, error) {
	rows, err := q.db.Query(ctx, getDiseaseTreatmentPlanWithPhases, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiseaseTreatmentPlanWithPhasesRow{}
	for rows.Next() {
		var i GetDiseaseTreatmentPlanWithPhasesRow
		if err := rows.Scan(
			&i.DiseaseID,
			&i.DiseaseName,
			&i.DiseaseDescription,
			&i.Symptoms,
			&i.PhaseName,
			&i.PhaseDescription,
			&i.MedicineID,
			&i.MedicineUsage,
			&i.MedicineName,
			&i.MedicineDescription,
			&i.PhaseID,
			&i.Dosage,
			&i.Frequency,
			&i.Duration,
			&i.SideEffects,
			&i.MedicineNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTreatmentByDiseaseId = `-- name: GetTreatmentByDiseaseId :many
SELECT 
    d.id AS disease_id,
    d.name AS disease_name,
    d.description AS disease_description,
    d.symptoms,
    tp.id AS phase_id,
    tp.phase_name AS phase_name,
    tp.description AS phase_description,
    m.id AS medicine_id,
    m.usage AS medicine_usage,
    m.name AS medicine_name,
    m.description AS medicine_description,
    COALESCE(pm.dosage, m.dosage) AS dosage,
    COALESCE(pm.frequency, m.frequency) AS frequency,
    COALESCE(pm.duration, m.duration) AS duration,
    m.side_effects
FROM diseases d
JOIN treatment_phases tp ON d.id = tp.disease_id
JOIN phase_medicines pm ON tp.id = pm.phase_id
JOIN medicines m ON pm.medicine_id = m.id
WHERE d.id = $1  LIMIT $2 OFFSET $3
`

type GetTreatmentByDiseaseIdParams struct {
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetTreatmentByDiseaseIdRow struct {
	DiseaseID           int64       `json:"disease_id"`
	DiseaseName         string      `json:"disease_name"`
	DiseaseDescription  pgtype.Text `json:"disease_description"`
	Symptoms            []byte      `json:"symptoms"`
	PhaseID             int64       `json:"phase_id"`
	PhaseName           pgtype.Text `json:"phase_name"`
	PhaseDescription    pgtype.Text `json:"phase_description"`
	MedicineID          int64       `json:"medicine_id"`
	MedicineUsage       pgtype.Text `json:"medicine_usage"`
	MedicineName        string      `json:"medicine_name"`
	MedicineDescription pgtype.Text `json:"medicine_description"`
	Dosage              pgtype.Text `json:"dosage"`
	Frequency           pgtype.Text `json:"frequency"`
	Duration            pgtype.Text `json:"duration"`
	SideEffects         pgtype.Text `json:"side_effects"`
}

func (q *Queries) GetTreatmentByDiseaseId(ctx context.Context, arg GetTreatmentByDiseaseIdParams) ([]GetTreatmentByDiseaseIdRow, error) {
	rows, err := q.db.Query(ctx, getTreatmentByDiseaseId, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTreatmentByDiseaseIdRow{}
	for rows.Next() {
		var i GetTreatmentByDiseaseIdRow
		if err := rows.Scan(
			&i.DiseaseID,
			&i.DiseaseName,
			&i.DiseaseDescription,
			&i.Symptoms,
			&i.PhaseID,
			&i.PhaseName,
			&i.PhaseDescription,
			&i.MedicineID,
			&i.MedicineUsage,
			&i.MedicineName,
			&i.MedicineDescription,
			&i.Dosage,
			&i.Frequency,
			&i.Duration,
			&i.SideEffects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
