// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

<<<<<<< HEAD
const createtNotification = `-- name: CreatetNotification :one
INSERT INTO notifications (
    username,
    title,
    content,
    notify_type,
    related_id,
    related_type,
    is_read
) VALUES (
    $1, $2, $3, $4, $5, $6, false
) RETURNING id, username, title, content, is_read, related_id, related_type, datetime, notify_type
`

type CreatetNotificationParams struct {
	Username    string      `json:"username"`
	Title       string      `json:"title"`
	Content     pgtype.Text `json:"content"`
	NotifyType  pgtype.Text `json:"notify_type"`
	RelatedID   pgtype.Int4 `json:"related_id"`
	RelatedType pgtype.Text `json:"related_type"`
}

func (q *Queries) CreatetNotification(ctx context.Context, arg CreatetNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createtNotification,
		arg.Username,
		arg.Title,
		arg.Content,
		arg.NotifyType,
		arg.RelatedID,
		arg.RelatedType,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Title,
		&i.Content,
		&i.IsRead,
		&i.RelatedID,
		&i.RelatedType,
		&i.Datetime,
		&i.NotifyType,
	)
	return i, err
}

const deleteNotificationsByUsername = `-- name: DeleteNotificationsByUsername :exec
DELETE FROM notifications
WHERE username = $1
`

func (q *Queries) DeleteNotificationsByUsername(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteNotificationsByUsername, username)
	return err
}

const listNotificationsByUsername = `-- name: ListNotificationsByUsername :many
SELECT id, username, title, content, is_read, related_id, related_type, datetime, notify_type FROM notifications
WHERE username = $1
LIMIT $2 OFFSET $3
`

type ListNotificationsByUsernameParams struct {
=======
const deleteAllNotifications = `-- name: DeleteAllNotifications :exec
DELETE FROM notifications
`

// Delete all notifications
func (q *Queries) DeleteAllNotifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllNotifications)
	return err
}

const getNotificationsByUsername = `-- name: GetNotificationsByUsername :many
SELECT notifications.notificationid, notifications.petid, notifications.title, notifications.body, notifications.duedate, notifications.repeatinterval, notifications.iscompleted, notifications.notificationsent
FROM notifications
JOIN pet ON notifications.petID = pet.petid
JOIN users ON pet.username = users.username
WHERE users.username = $1
ORDER BY notifications.dueDate DESC
LIMIT $2 OFFSET $3
`

type GetNotificationsByUsernameParams struct {
>>>>>>> eb8d761 (updated pet schedule)
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

<<<<<<< HEAD
func (q *Queries) ListNotificationsByUsername(ctx context.Context, arg ListNotificationsByUsernameParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUsername, arg.Username, arg.Limit, arg.Offset)
=======
func (q *Queries) GetNotificationsByUsername(ctx context.Context, arg GetNotificationsByUsernameParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByUsername, arg.Username, arg.Limit, arg.Offset)
>>>>>>> eb8d761 (updated pet schedule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
<<<<<<< HEAD
			&i.ID,
			&i.Username,
			&i.Title,
			&i.Content,
			&i.IsRead,
			&i.RelatedID,
			&i.RelatedType,
			&i.Datetime,
			&i.NotifyType,
=======
			&i.Notificationid,
			&i.Petid,
			&i.Title,
			&i.Body,
			&i.Duedate,
			&i.Repeatinterval,
			&i.Iscompleted,
			&i.Notificationsent,
>>>>>>> eb8d761 (updated pet schedule)
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

<<<<<<< HEAD
const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET is_read = true
WHERE id = $1
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, id)
	return err
=======
const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (petID, title, body, dueDate, repeatInterval, isCompleted, notificationSent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING notificationid, petid, title, body, duedate, repeatinterval, iscompleted, notificationsent
`

type InsertNotificationParams struct {
	Petid            pgtype.Int8      `json:"petid"`
	Title            string           `json:"title"`
	Body             pgtype.Text      `json:"body"`
	Duedate          pgtype.Timestamp `json:"duedate"`
	Repeatinterval   pgtype.Text      `json:"repeatinterval"`
	Iscompleted      pgtype.Bool      `json:"iscompleted"`
	Notificationsent pgtype.Bool      `json:"notificationsent"`
}

// Insert a notification
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.Petid,
		arg.Title,
		arg.Body,
		arg.Duedate,
		arg.Repeatinterval,
		arg.Iscompleted,
		arg.Notificationsent,
	)
	var i Notification
	err := row.Scan(
		&i.Notificationid,
		&i.Petid,
		&i.Title,
		&i.Body,
		&i.Duedate,
		&i.Repeatinterval,
		&i.Iscompleted,
		&i.Notificationsent,
	)
	return i, err
>>>>>>> eb8d761 (updated pet schedule)
}
