// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CountingComponentsByUser(ctx context.Context, arg CountingComponentsByUserParams) (int64, error)
	CreateComponents(ctx context.Context, arg CreateComponentsParams) (Component, error)
	CreatePage(ctx context.Context, arg CreatePageParams) (Page, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteComponents(ctx context.Context, id int64) (Component, error)
	DeletePage(ctx context.Context, id int64) (Page, error)
	DeleteProject(ctx context.Context, id int64) (Project, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetComponentsById(ctx context.Context, arg GetComponentsByIdParams) (Component, error)
	GetComponentsByName(ctx context.Context, name string) (Component, error)
	GetComponentsByUser(ctx context.Context, arg GetComponentsByUserParams) ([]GetComponentsByUserRow, error)
	GetComponentss(ctx context.Context) ([]Component, error)
	GetPages(ctx context.Context) ([]Page, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectsByUser(ctx context.Context, username string) ([]Project, error)
	GetUser(ctx context.Context, username string) (User, error)
	RemoveComponents(ctx context.Context, arg RemoveComponentsParams) (Component, error)
	UpdateComponents(ctx context.Context, arg UpdateComponentsParams) (Component, error)
	UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error)
	UpdatePlanType(ctx context.Context, arg UpdatePlanTypeParams) (User, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
