// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: reminder.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReminder = `-- name: CreateReminder :one
INSERT INTO Reminders (
    PetID,
    Title,
    Description,
    DueDate,
    RepeatInterval
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING reminderid, petid, title, description, duedate, repeatinterval, iscompleted, notificationsent
`

type CreateReminderParams struct {
	Petid          pgtype.Int8      `json:"petid"`
	Title          string           `json:"title"`
	Description    pgtype.Text      `json:"description"`
	Duedate        pgtype.Timestamp `json:"duedate"`
	Repeatinterval pgtype.Text      `json:"repeatinterval"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.Petid,
		arg.Title,
		arg.Description,
		arg.Duedate,
		arg.Repeatinterval,
	)
	var i Reminder
	err := row.Scan(
		&i.Reminderid,
		&i.Petid,
		&i.Title,
		&i.Description,
		&i.Duedate,
		&i.Repeatinterval,
		&i.Iscompleted,
		&i.Notificationsent,
	)
	return i, err
}
