// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: reminder.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReminder = `-- name: CreateReminder :one
INSERT INTO Reminder (
    UserID,
    PetID,
    ReminderType,
    ReminderDate,
    Description,
    Status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING reminderid, userid, petid, remindertype, reminderdate, description, status
`

type CreateReminderParams struct {
	Userid       pgtype.Int8 `json:"userid"`
	Petid        pgtype.Int8 `json:"petid"`
	Remindertype string      `json:"remindertype"`
	Reminderdate pgtype.Date `json:"reminderdate"`
	Description  pgtype.Text `json:"description"`
	Status       pgtype.Text `json:"status"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.Userid,
		arg.Petid,
		arg.Remindertype,
		arg.Reminderdate,
		arg.Description,
		arg.Status,
	)
	var i Reminder
	err := row.Scan(
		&i.Reminderid,
		&i.Userid,
		&i.Petid,
		&i.Remindertype,
		&i.Reminderdate,
		&i.Description,
		&i.Status,
	)
	return i, err
}
