// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: service.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
<<<<<<< HEAD
<<<<<<< HEAD
    name, description, duration, cost, category
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, description, duration, cost, category, priority, created_at
=======
    name, description, duration, cost, category, notes
=======
    name, description, duration, cost, category
>>>>>>> ada3717 (Docker file)
) VALUES (
    $1, $2, $3, $4, $5
)
<<<<<<< HEAD
RETURNING id, name, description, duration, cost, category, notes, created_at, updated_at
>>>>>>> b393bb9 (add service and add permission)
=======
RETURNING id, name, description, duration, cost, category, priority, created_at
>>>>>>> ada3717 (Docker file)
`

type CreateServiceParams struct {
	Name        pgtype.Text   `json:"name"`
	Description pgtype.Text   `json:"description"`
	Duration    pgtype.Int2   `json:"duration"`
	Cost        pgtype.Float8 `json:"cost"`
	Category    pgtype.Text   `json:"category"`
<<<<<<< HEAD
<<<<<<< HEAD
=======
	Notes       pgtype.Text   `json:"notes"`
>>>>>>> b393bb9 (add service and add permission)
=======
>>>>>>> ada3717 (Docker file)
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.Description,
		arg.Duration,
		arg.Cost,
		arg.Category,
<<<<<<< HEAD
<<<<<<< HEAD
=======
		arg.Notes,
>>>>>>> b393bb9 (add service and add permission)
=======
>>>>>>> ada3717 (Docker file)
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Duration,
		&i.Cost,
		&i.Category,
<<<<<<< HEAD
<<<<<<< HEAD
		&i.Priority,
		&i.CreatedAt,
=======
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
>>>>>>> b393bb9 (add service and add permission)
=======
		&i.Priority,
		&i.CreatedAt,
>>>>>>> ada3717 (Docker file)
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
UPDATE services
SET removed_at = NOW()
<<<<<<< HEAD
<<<<<<< HEAD
WHERE id = $1
=======
WHERE id = $1 and removed_at is NULL
>>>>>>> b393bb9 (add service and add permission)
=======
WHERE id = $1
>>>>>>> ffc9071 (AI suggestion)
`

func (q *Queries) DeleteService(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

<<<<<<< HEAD
<<<<<<< HEAD
const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, description, duration, cost, category, priority, created_at FROM services
WHERE id = $1
=======
const getAllServices = `-- name: GetAllServices :many
SELECT serviceid, typeid, name, price, duration, description, isavailable, removed_at FROM Service ORDER BY name LIMIT $1 OFFSET $2
>>>>>>> 5e493e4 (get all services)
=======
const getServiceByID = `-- name: GetServiceByID :one
<<<<<<< HEAD
SELECT id, name, description, duration, cost, category, notes, created_at, updated_at FROM services
<<<<<<< HEAD
WHERE id = $1 and removed_at is NULL
>>>>>>> b393bb9 (add service and add permission)
=======
=======
SELECT id, name, description, duration, cost, category, priority, created_at FROM services
>>>>>>> ada3717 (Docker file)
WHERE id = $1
>>>>>>> ffc9071 (AI suggestion)
`

func (q *Queries) GetServiceByID(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Duration,
		&i.Cost,
		&i.Category,
<<<<<<< HEAD
<<<<<<< HEAD
		&i.Priority,
		&i.CreatedAt,
=======
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
>>>>>>> b393bb9 (add service and add permission)
=======
		&i.Priority,
		&i.CreatedAt,
>>>>>>> ada3717 (Docker file)
	)
	return i, err
}

const getServices = `-- name: GetServices :many
<<<<<<< HEAD
<<<<<<< HEAD
SELECT id, name, description, duration, cost, category, priority, created_at FROM services where removed_at is NULL ORDER BY name LIMIT $1 OFFSET $2
=======
SELECT id, name, description, duration, cost, category, notes, created_at, updated_at FROM services where removed_at is NULL ORDER BY name LIMIT $1 OFFSET $2
>>>>>>> b393bb9 (add service and add permission)
=======
SELECT id, name, description, duration, cost, category, priority, created_at FROM services where removed_at is NULL ORDER BY name LIMIT $1 OFFSET $2
>>>>>>> ada3717 (Docker file)
`

type GetServicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetServices(ctx context.Context, arg GetServicesParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, getServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Duration,
			&i.Cost,
			&i.Category,
<<<<<<< HEAD
<<<<<<< HEAD
			&i.Priority,
			&i.CreatedAt,
=======
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
>>>>>>> b393bb9 (add service and add permission)
=======
			&i.Priority,
			&i.CreatedAt,
>>>>>>> ada3717 (Docker file)
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> b393bb9 (add service and add permission)
const updateService = `-- name: UpdateService :one
UPDATE services
SET 
    name = $2,
    description = $3,
    duration = $4,
    cost = $5,
    category = $6,
<<<<<<< HEAD
<<<<<<< HEAD
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, duration, cost, category, priority, created_at
=======
const getServiceByID = `-- name: GetServiceByID :one
SELECT serviceid, typeid, name, price, duration, description, isavailable, removed_at FROM Service 
WHERE serviceID = $1 LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, serviceid int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, serviceid)
	var i Service
	err := row.Scan(
		&i.Serviceid,
		&i.Typeid,
		&i.Name,
		&i.Price,
		&i.Duration,
		&i.Description,
		&i.Isavailable,
		&i.RemovedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :exec
UPDATE Service Set
  typeID = $2,
  name = $3,
  price = $4,
  duration = $5,
  description = $6,
  isAvailable = $7
WHERE serviceID = $1
>>>>>>> 5ea33aa (PUT pet info)
=======
    notes = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, duration, cost, category, notes, created_at, updated_at
>>>>>>> b393bb9 (add service and add permission)
=======
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, duration, cost, category, priority, created_at
>>>>>>> ada3717 (Docker file)
`

type UpdateServiceParams struct {
	ID          int64         `json:"id"`
	Name        pgtype.Text   `json:"name"`
	Description pgtype.Text   `json:"description"`
	Duration    pgtype.Int2   `json:"duration"`
	Cost        pgtype.Float8 `json:"cost"`
	Category    pgtype.Text   `json:"category"`
<<<<<<< HEAD
<<<<<<< HEAD
=======
	Notes       pgtype.Text   `json:"notes"`
>>>>>>> b393bb9 (add service and add permission)
=======
>>>>>>> ada3717 (Docker file)
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Duration,
		arg.Cost,
		arg.Category,
<<<<<<< HEAD
<<<<<<< HEAD
=======
		arg.Notes,
>>>>>>> b393bb9 (add service and add permission)
=======
>>>>>>> ada3717 (Docker file)
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Duration,
		&i.Cost,
		&i.Category,
<<<<<<< HEAD
<<<<<<< HEAD
		&i.Priority,
		&i.CreatedAt,
=======
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
>>>>>>> b393bb9 (add service and add permission)
=======
		&i.Priority,
		&i.CreatedAt,
>>>>>>> ada3717 (Docker file)
	)
	return i, err
}
